### ISSUE TITLE
why does the option "Logback: use slf4j-jdk14 instead" make app faster?

### ISSUE THREAD

**Issue by exceptionplayer** [dsyer/spring-boot-allocations#1]
why does the option "Logback: use slf4j-jdk14 instead" make app faster?

**Comment by gandrade** [comment]
I think Dave's point about using `slf4j-jdk14` instead of `spring-boot-starter-logging` it to make application classloader as smaller as possible, and as a consequence, making application starts up faster.

**Comment by exceptionplayer** [comment]
> I think Dave's point about using `slf4j-jdk14` instead of `spring-boot-starter-logging` it to make application classloader as smaller as possible, and as a consequence, making application starts up faster.

Sounds reasonable, thanks~
